Repository speezy98/cookmaster, pull requests merged in 2023-11, with the labels that each got.

#2 Ajout des templates issue feature request et bug
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#4 Ajout du template de pull request
  .github/MERGE_REQUEST_TEMPLATE/pul_request_template.md
Labels: template

#8 Réparation du template de pull request
  .github/pull_request_template.md
Labels: bug

#6 Hook
  commit-msg
Labels: enhancement

#14 Ajout du code of conduct
  code_of_conduct.md
Labels: documentation

#12 Readme
  Readme.md
Labels: documentation

#13 Ajout du contributing
  contributing.md
Labels: documentation

#17 Ajout d'un menu de recette sur la page d'accueil
  .gitignore
  index.php
  package-lock.json
  package.json
  public/index.php
  public/menu.js
Labels: enhancement

#19 Correction des templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug

#21 Mise en place de la connexion à la base de donnée
  database/connection.php
  database/migration.php
Labels: enhancement

#38 Ajout de la page d'inscription
  public/register.php
Labels: enhancement

#37 page de connexion
  public/connexion.php
Labels: enhancement

#40 Page d'affichage des recettes et des commentaires
  public/recettes.js
Labels: enhancement

#43 Ajout d'une page de profil
  public/profil.js
  public/profil.php
Labels: enhancement

#44 Merger develop sur main (première version du site web)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  Readme.md
  code_of_conduct.md
  commit-msg
  contributing.md
  database/connection.php
  database/migration.php
  index.php
  package-lock.json
  package.json
  public/community.js
  public/connexion.php
  public/index.php
  public/menu.js
  public/profil.js
  public/profil.php
  public/recettes.js
  public/register.php
  public/subscribe.php
Labels: merge develop

#48 Correction de l'affichage
  public/assets/css/style.css
  public/assets/js/community.js
  public/assets/js/menu.js
  public/assets/js/profil.js
  public/assets/js/recettes.js
Labels: bug

#50 Correction du bug de la partie commentaire
  public/assets/js/recettes.js
Labels: bug

#51 Correction des failles XSS et d'injection SQL
  .gitignore
  public/failles/sql.php
  public/failles/xss.js
Labels: bug

#52 merge develop ( Corrections de bugs)
  .gitignore
  public/assets/css/style.css
  public/assets/js/community.js
  public/assets/js/menu.js
  public/assets/js/profil.js
  public/assets/js/recettes.js
  public/failles/sql.php
  public/failles/xss.js
  public/recettes.js
Labels: merge develop

#55 Mise en place d'un barre de recherche avec JQuery
  public/index.php
Labels: enhancement

#54 Ajout d'une partie favoris
  public/assets/js/favoris.js
Labels: enhancement

#57 Notification par Mail
  public/assets/js/mail.js
Labels: enhancement

#58 Mise en place de la gestion des images
  public/assets/img/nutrition.jpg
  public/assets/img/pyramide-alimentaire.jpg
  public/img.md
Labels: enhancement

#59 Mise en place du partage
  public/send.php
Labels: enhancement

#60 Merge develop (nouvelles fonctionnalités)
  public/assets/img/nutrition.jpg
  public/assets/img/pyramide-alimentaire.jpg
  public/assets/js/favoris.js
  public/assets/js/mail.js
  public/assets/js/notification.js
  public/assets/js/tutorial.js
  public/img.md
  public/index.php
  public/send.php
Labels: merge develop

#61 Mise en place d'une api qui récupère les recettes
  .gitignore
  api_spoonacular/.gitignore
  api_spoonacular/.htaccess
  api_spoonacular/README.md
  api_spoonacular/database/connection.php
  api_spoonacular/entities/members/create-member.php
  api_spoonacular/entities/members/delete-member.php
  api_spoonacular/entities/members/get-members.php
  api_spoonacular/entities/members/is-member-logged-in.php
  api_spoonacular/entities/members/login-member.php
  api_spoonacular/entities/members/logout-member.php
  api_spoonacular/entities/members/register-member.php
  api_spoonacular/entities/members/update-member.php
  api_spoonacular/index.php
  api_spoonacular/libraries/body.php
  api_spoonacular/libraries/header.php
  api_spoonacular/libraries/method.php
  api_spoonacular/libraries/parameters.php
  api_spoonacular/libraries/path.php
  api_spoonacular/libraries/response.php
  api_spoonacular/migrations/migration.php
  api_spoonacular/routes/authentification/login.php
  api_spoonacular/routes/authentification/logout.php
  api_spoonacular/routes/authentification/register.php
  api_spoonacular/routes/members/delete.php
  api_spoonacular/routes/members/get.php
  api_spoonacular/routes/members/patch.php
  api_spoonacular/routes/members/post.php
  api_spoonacular/routes/not-found/all.php
Labels: enhancement

#62 Mise en prod de l'api
  .gitignore
  api_spoonacular/.gitignore
  api_spoonacular/.htaccess
  api_spoonacular/README.md
  api_spoonacular/database/connection.php
  api_spoonacular/entities/members/create-member.php
  api_spoonacular/entities/members/delete-member.php
  api_spoonacular/entities/members/get-members.php
  api_spoonacular/entities/members/is-member-logged-in.php
  api_spoonacular/entities/members/login-member.php
  api_spoonacular/entities/members/logout-member.php
  api_spoonacular/entities/members/register-member.php
  api_spoonacular/entities/members/update-member.php
  api_spoonacular/index.php
  api_spoonacular/libraries/body.php
  api_spoonacular/libraries/header.php
  api_spoonacular/libraries/method.php
  api_spoonacular/libraries/parameters.php
  api_spoonacular/libraries/path.php
  api_spoonacular/libraries/response.php
  api_spoonacular/migrations/migration.php
  api_spoonacular/routes/authentification/login.php
  api_spoonacular/routes/authentification/logout.php
  api_spoonacular/routes/authentification/register.php
  api_spoonacular/routes/members/delete.php
  api_spoonacular/routes/members/get.php
  api_spoonacular/routes/members/patch.php
  api_spoonacular/routes/members/post.php
  api_spoonacular/routes/not-found/all.php
Labels: mise en prod

#65 Mise en place de la vérification js
  .eslintrc.js
  .eslintrc.yml
  package.json
Labels: enhancement

#69 Mise en place du github action
  action.yml
  index.js
  package-lock.json
  package.json
Labels: enhancement
